// <auto-generated />
using System;
using HinataProject.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HinataProject.Persistence.Migrations
{
    [DbContext(typeof(HinataProjectDataContext))]
    [Migration("20260226151015_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HinataProject.Persistence.Entities.AuditLogEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("property_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log_entries");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_audit_log_entries_node_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_log_entries_user_id");

                    b.ToTable("audit_log_entries", (string)null);
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.CommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_comments_node_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comments_user_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.NodeAddedRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_node_added_roles");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_node_added_roles_node_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_node_added_roles_role_id");

                    b.ToTable("node_added_roles", (string)null);
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.NodeAddedTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("pk_node_added_types");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_node_added_types_node_id");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_node_added_types_type_id");

                    b.ToTable("node_added_types", (string)null);
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.NodeAddedWorkflowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_node_added_workflows");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_node_added_workflows_node_id");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_node_added_workflows_workflow_id");

                    b.ToTable("node_added_workflows", (string)null);
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.NodeAssigneeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_node_assignees");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_node_assignees_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_node_assignees_user_id");

                    b.HasIndex("NodeId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_node_assignees_node_id_role_id");

                    b.ToTable("node_assignees", (string)null);
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.NodeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Instant>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("Manifest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manifest");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("PublicId")
                        .HasColumnType("integer")
                        .HasColumnName("public_id");

                    b.Property<Guid?>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_id");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_nodes");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_nodes_parent_id");

                    b.HasIndex("StateId")
                        .HasDatabaseName("ix_nodes_state_id");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_nodes_type_id");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_nodes_workflow_id");

                    b.ToTable("nodes", (string)null);
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.NodeRemovedRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_node_removed_roles");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_node_removed_roles_node_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_node_removed_roles_role_id");

                    b.ToTable("node_removed_roles", (string)null);
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.NodeRemovedTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("pk_node_removed_types");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_node_removed_types_node_id");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_node_removed_types_type_id");

                    b.ToTable("node_removed_types", (string)null);
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.NodeRemovedWorkflowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_node_removed_workflows");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_node_removed_workflows_node_id");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_node_removed_workflows_workflow_id");

                    b.ToTable("node_removed_workflows", (string)null);
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Rights")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rights");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.StateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsFinalFailure")
                        .HasColumnType("boolean")
                        .HasColumnName("is_final_failure");

                    b.Property<bool>("IsFinalSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_final_success");

                    b.Property<Instant>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_states");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_states_workflow_id");

                    b.ToTable("states", (string)null);
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.TypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Instant>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_types");

                    b.ToTable("types", (string)null);
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("info");

                    b.Property<Instant>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.UserRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_roles_user_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.WorkflowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DefaultStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_state_id");

                    b.Property<Instant>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.HasIndex("DefaultStateId")
                        .HasDatabaseName("ix_workflows_default_state_id");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("RoleEntityStateEntity", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid")
                        .HasColumnName("roles_id");

                    b.Property<Guid>("StatesId")
                        .HasColumnType("uuid")
                        .HasColumnName("states_id");

                    b.HasKey("RolesId", "StatesId")
                        .HasName("pk_role_states");

                    b.HasIndex("StatesId")
                        .HasDatabaseName("ix_role_states_states_id");

                    b.ToTable("role_states", (string)null);
                });

            modelBuilder.Entity("TypeEntityWorkflowEntity", b =>
                {
                    b.Property<Guid>("DefaultForTypesId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_for_types_id");

                    b.Property<Guid>("DefaultForTypesWorkflowsId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_for_types_workflows_id");

                    b.HasKey("DefaultForTypesId", "DefaultForTypesWorkflowsId")
                        .HasName("pk_workflow_default_for_types");

                    b.HasIndex("DefaultForTypesWorkflowsId")
                        .HasDatabaseName("ix_workflow_default_for_types_default_for_types_workflows_id");

                    b.ToTable("workflow_default_for_types", (string)null);
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.AuditLogEntryEntity", b =>
                {
                    b.HasOne("HinataProject.Persistence.Entities.NodeEntity", "Node")
                        .WithMany("AuditLogEntries")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_entries_nodes_node_id");

                    b.HasOne("HinataProject.Persistence.Entities.UserEntity", "User")
                        .WithMany("AuditLogEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_entries_users_user_id");

                    b.Navigation("Node");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.CommentEntity", b =>
                {
                    b.HasOne("HinataProject.Persistence.Entities.NodeEntity", "Node")
                        .WithMany("Comments")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_nodes_node_id");

                    b.HasOne("HinataProject.Persistence.Entities.UserEntity", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_user_id");

                    b.Navigation("Node");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.NodeAddedRoleEntity", b =>
                {
                    b.HasOne("HinataProject.Persistence.Entities.NodeEntity", "Node")
                        .WithMany("AddedRoles")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_added_roles_nodes_node_id");

                    b.HasOne("HinataProject.Persistence.Entities.RoleEntity", "Role")
                        .WithMany("AddedRoleNodes")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_added_roles_roles_role_id");

                    b.Navigation("Node");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.NodeAddedTypeEntity", b =>
                {
                    b.HasOne("HinataProject.Persistence.Entities.NodeEntity", "Node")
                        .WithMany("AddedTypes")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_added_types_nodes_node_id");

                    b.HasOne("HinataProject.Persistence.Entities.TypeEntity", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_added_types_types_type_id");

                    b.Navigation("Node");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.NodeAddedWorkflowEntity", b =>
                {
                    b.HasOne("HinataProject.Persistence.Entities.NodeEntity", "Node")
                        .WithMany("AddedWorkflows")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_added_workflows_nodes_node_id");

                    b.HasOne("HinataProject.Persistence.Entities.WorkflowEntity", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_added_workflows_workflows_workflow_id");

                    b.Navigation("Node");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.NodeAssigneeEntity", b =>
                {
                    b.HasOne("HinataProject.Persistence.Entities.NodeEntity", "Node")
                        .WithMany("Assignees")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_assignees_nodes_node_id");

                    b.HasOne("HinataProject.Persistence.Entities.RoleEntity", "Role")
                        .WithMany("NodeAssignees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_assignees_roles_role_id");

                    b.HasOne("HinataProject.Persistence.Entities.UserEntity", "User")
                        .WithMany("NodeAssignees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_assignees_users_user_id");

                    b.Navigation("Node");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.NodeEntity", b =>
                {
                    b.HasOne("HinataProject.Persistence.Entities.NodeEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_nodes_nodes_parent_id");

                    b.HasOne("HinataProject.Persistence.Entities.StateEntity", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_nodes_states_state_id");

                    b.HasOne("HinataProject.Persistence.Entities.TypeEntity", "Type")
                        .WithMany("Nodes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_nodes_types_type_id");

                    b.HasOne("HinataProject.Persistence.Entities.WorkflowEntity", "Workflow")
                        .WithMany("Nodes")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_nodes_workflows_workflow_id");

                    b.Navigation("Parent");

                    b.Navigation("State");

                    b.Navigation("Type");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.NodeRemovedRoleEntity", b =>
                {
                    b.HasOne("HinataProject.Persistence.Entities.NodeEntity", "Node")
                        .WithMany("RemovedRoles")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_removed_roles_nodes_node_id");

                    b.HasOne("HinataProject.Persistence.Entities.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_removed_roles_roles_role_id");

                    b.Navigation("Node");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.NodeRemovedTypeEntity", b =>
                {
                    b.HasOne("HinataProject.Persistence.Entities.NodeEntity", "Node")
                        .WithMany("RemovedTypes")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_removed_types_nodes_node_id");

                    b.HasOne("HinataProject.Persistence.Entities.TypeEntity", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_removed_types_types_type_id");

                    b.Navigation("Node");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.NodeRemovedWorkflowEntity", b =>
                {
                    b.HasOne("HinataProject.Persistence.Entities.NodeEntity", "Node")
                        .WithMany("RemovedWorkflows")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_removed_workflows_nodes_node_id");

                    b.HasOne("HinataProject.Persistence.Entities.WorkflowEntity", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_removed_workflows_workflows_workflow_id");

                    b.Navigation("Node");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.StateEntity", b =>
                {
                    b.HasOne("HinataProject.Persistence.Entities.WorkflowEntity", "Workflow")
                        .WithMany("States")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_states_workflows_workflow_id");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("HinataProject.Persistence.Entities.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("HinataProject.Persistence.Entities.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.WorkflowEntity", b =>
                {
                    b.HasOne("HinataProject.Persistence.Entities.StateEntity", "DefaultState")
                        .WithMany()
                        .HasForeignKey("DefaultStateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workflows_states_default_state_id");

                    b.Navigation("DefaultState");
                });

            modelBuilder.Entity("RoleEntityStateEntity", b =>
                {
                    b.HasOne("HinataProject.Persistence.Entities.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_states_roles_roles_id");

                    b.HasOne("HinataProject.Persistence.Entities.StateEntity", null)
                        .WithMany()
                        .HasForeignKey("StatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_states_states_states_id");
                });

            modelBuilder.Entity("TypeEntityWorkflowEntity", b =>
                {
                    b.HasOne("HinataProject.Persistence.Entities.TypeEntity", null)
                        .WithMany()
                        .HasForeignKey("DefaultForTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_default_for_types_types_default_for_types_id");

                    b.HasOne("HinataProject.Persistence.Entities.WorkflowEntity", null)
                        .WithMany()
                        .HasForeignKey("DefaultForTypesWorkflowsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_default_for_types_workflows_default_for_types_work");
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.NodeEntity", b =>
                {
                    b.Navigation("AddedRoles");

                    b.Navigation("AddedTypes");

                    b.Navigation("AddedWorkflows");

                    b.Navigation("Assignees");

                    b.Navigation("AuditLogEntries");

                    b.Navigation("Children");

                    b.Navigation("Comments");

                    b.Navigation("RemovedRoles");

                    b.Navigation("RemovedTypes");

                    b.Navigation("RemovedWorkflows");
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.RoleEntity", b =>
                {
                    b.Navigation("AddedRoleNodes");

                    b.Navigation("NodeAssignees");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.TypeEntity", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("AuditLogEntries");

                    b.Navigation("Comments");

                    b.Navigation("NodeAssignees");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HinataProject.Persistence.Entities.WorkflowEntity", b =>
                {
                    b.Navigation("Nodes");

                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
